name: Deploy to Vercel

on:
      push:
            branches:
                  - main # deploy only when pushing to main

jobs:
      deploy:
            runs-on: ubuntu-latest

            steps:
                  - name: Checkout code
                    uses: actions/checkout@v4

                  - name: Install dependencies
                    run: npm install

                  - name: Build project
                    run: npm run build

                  - name: Deploy to Vercel
                    run: |
                          npm install -g vercel
                          vercel --prod \
                            --token=$VERCEL_TOKEN \
                            --scope=$VERCEL_ORG_ID \
                            --confirm --cwd . \
                            --project=$VERCEL_PROJECT_ID
